// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6Wmj88dmpWIgGsalOKBXap2singvoBE',
    appId: '1:1077617993688:web:e8536f84a81f4939c5f4ad',
    messagingSenderId: '1077617993688',
    projectId: 'nappybackend',
    authDomain: 'nappybackend.firebaseapp.com',
    storageBucket: 'nappybackend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvcf2N0ee-8HmGIUw-KBHgUBmtf1C9SNA',
    appId: '1:1077617993688:android:99092698c7d3ee55c5f4ad',
    messagingSenderId: '1077617993688',
    projectId: 'nappybackend',
    storageBucket: 'nappybackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_b5EQgKn5lpRNPpzPyP33_1Br363zOE',
    appId: '1:1077617993688:ios:8e09aec0fa51c278c5f4ad',
    messagingSenderId: '1077617993688',
    projectId: 'nappybackend',
    storageBucket: 'nappybackend.appspot.com',
    androidClientId: '1077617993688-br2igk0ibsti110tlqltvcj6devecn0t.apps.googleusercontent.com',
    iosClientId: '1077617993688-07tk6vf3cd3b3g8en8hifaj0pjuldjv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nappyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_b5EQgKn5lpRNPpzPyP33_1Br363zOE',
    appId: '1:1077617993688:ios:46c422367aa49a62c5f4ad',
    messagingSenderId: '1077617993688',
    projectId: 'nappybackend',
    storageBucket: 'nappybackend.appspot.com',
    androidClientId: '1077617993688-br2igk0ibsti110tlqltvcj6devecn0t.apps.googleusercontent.com',
    iosClientId: '1077617993688-g1pahu628ang3s66acjok2u2e5ei0pqg.apps.googleusercontent.com',
    iosBundleId: 'com.nappy.cards.nappyMobile',
  );
}
